/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ApiRouteImport } from './routes/api'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as VerificationsRouteImport } from './routes/verifications'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as BillingHistoryRouteImport } from './routes/billing.history'
import { Route as BillingTopUpRouteImport } from './routes/billing.top-up'
import { Route as VerificationsIndexRouteImport } from './routes/verifications.index'
import { Route as VerificationsIdRouteImport } from './routes/verifications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationsRoute = VerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillingRoute,
} as any)
const BillingHistoryRoute = BillingHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BillingRoute,
} as any)
const BillingTopUpRoute = BillingTopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => BillingRoute,
} as any)
const VerificationsIndexRoute = VerificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerificationsRoute,
} as any)
const VerificationsIdRoute = VerificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VerificationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRoute
  '/billing': typeof BillingRouteWithChildren
  '/bulk': typeof BulkRoute
  '/customers': typeof CustomersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/verifications': typeof VerificationsRouteWithChildren
  '/verify': typeof VerifyRoute
  '/billing/history': typeof BillingHistoryRoute
  '/billing/top-up': typeof BillingTopUpRoute
  '/verifications/$id': typeof VerificationsIdRoute
  '/billing/': typeof BillingIndexRoute
  '/verifications/': typeof VerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRoute
  '/bulk': typeof BulkRoute
  '/customers': typeof CustomersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/verify': typeof VerifyRoute
  '/billing/history': typeof BillingHistoryRoute
  '/billing/top-up': typeof BillingTopUpRoute
  '/verifications/$id': typeof VerificationsIdRoute
  '/billing': typeof BillingIndexRoute
  '/verifications': typeof VerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRoute
  '/billing': typeof BillingRouteWithChildren
  '/bulk': typeof BulkRoute
  '/customers': typeof CustomersRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/verifications': typeof VerificationsRouteWithChildren
  '/verify': typeof VerifyRoute
  '/billing/history': typeof BillingHistoryRoute
  '/billing/top-up': typeof BillingTopUpRoute
  '/verifications/$id': typeof VerificationsIdRoute
  '/billing/': typeof BillingIndexRoute
  '/verifications/': typeof VerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/api'
    | '/billing'
    | '/bulk'
    | '/customers'
    | '/profile'
    | '/settings'
    | '/support'
    | '/team'
    | '/verifications'
    | '/verify'
    | '/billing/history'
    | '/billing/top-up'
    | '/verifications/$id'
    | '/billing/'
    | '/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/api'
    | '/bulk'
    | '/customers'
    | '/profile'
    | '/settings'
    | '/support'
    | '/team'
    | '/verify'
    | '/billing/history'
    | '/billing/top-up'
    | '/verifications/$id'
    | '/billing'
    | '/verifications'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/api'
    | '/billing'
    | '/bulk'
    | '/customers'
    | '/profile'
    | '/settings'
    | '/support'
    | '/team'
    | '/verifications'
    | '/verify'
    | '/billing/history'
    | '/billing/top-up'
    | '/verifications/$id'
    | '/billing/'
    | '/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ApiRoute: typeof ApiRoute
  BillingRoute: typeof BillingRouteWithChildren
  BulkRoute: typeof BulkRoute
  CustomersRoute: typeof CustomersRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  VerificationsRoute: typeof VerificationsRouteWithChildren
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifications': {
      id: '/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof VerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/history': {
      id: '/billing/history'
      path: '/history'
      fullPath: '/billing/history'
      preLoaderRoute: typeof BillingHistoryRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/top-up': {
      id: '/billing/top-up'
      path: '/top-up'
      fullPath: '/billing/top-up'
      preLoaderRoute: typeof BillingTopUpRouteImport
      parentRoute: typeof BillingRoute
    }
    '/verifications/': {
      id: '/verifications/'
      path: '/'
      fullPath: '/verifications/'
      preLoaderRoute: typeof VerificationsIndexRouteImport
      parentRoute: typeof VerificationsRoute
    }
    '/verifications/$id': {
      id: '/verifications/$id'
      path: '/$id'
      fullPath: '/verifications/$id'
      preLoaderRoute: typeof VerificationsIdRouteImport
      parentRoute: typeof VerificationsRoute
    }
  }
}

interface BillingRouteChildren {
  BillingHistoryRoute: typeof BillingHistoryRoute
  BillingTopUpRoute: typeof BillingTopUpRoute
  BillingIndexRoute: typeof BillingIndexRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingHistoryRoute: BillingHistoryRoute,
  BillingTopUpRoute: BillingTopUpRoute,
  BillingIndexRoute: BillingIndexRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface VerificationsRouteChildren {
  VerificationsIdRoute: typeof VerificationsIdRoute
  VerificationsIndexRoute: typeof VerificationsIndexRoute
}

const VerificationsRouteChildren: VerificationsRouteChildren = {
  VerificationsIdRoute: VerificationsIdRoute,
  VerificationsIndexRoute: VerificationsIndexRoute,
}

const VerificationsRouteWithChildren = VerificationsRoute._addFileChildren(
  VerificationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ApiRoute: ApiRoute,
  BillingRoute: BillingRouteWithChildren,
  BulkRoute: BulkRoute,
  CustomersRoute: CustomersRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  VerificationsRoute: VerificationsRouteWithChildren,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
